// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijbnzuidywsurxcfffsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqYm56dWlkeXdzdXJ4Y2ZmZnNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MDU0NjEsImV4cCI6MjA2MDA4MTQ2MX0.4AmmtxHo5j4v_qoG_IjIASGUiOgPltmaJBGfi5m1dr8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);